a=input("enter num 1")
b=input("enter num 2")
c=int(a)+int(b)
print("the sum is",c)
d=int(a)-int(b)
print("the difference is",d)
e=int(a)*int(b)     
print("the product is",e)
f=int(a)/int(b)
print("the division is",f)